/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.java.gradle.lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
